apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-application
  namespace: openshift-gitops

spec:
  project: default

  source:
    repoURL: https://github.com/diesello/argo_demo.git
    targetRevision: HEAD
    path: nginx
    
  destination: 
    server: https://kubernetes.default.svc
    namespace: nginx

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
